name: Build
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
      - uses: actions/checkout@v2
          Run
      
      - name: Use Node.js
      - uses: actions/setup-node@v2
          Run
          node-version:'16'
          
      - name: Install dependencies
        run: yarn --immutable
        
      - name: Run tests
        run: yarn test
